### PR TITLE
Genesis camino local configuration

### PR DESCRIPTION
**Pull request by charalarg**
## Description ##
This RP introduces a new networkID in the configurations (caminoLocal) and a new genesis file in order to be able to setup a local network with the latest genesis changes. In order to run the `camino-node` according to the `genesis-camino-local.json` the `network-id` argument should be set as shown here `--network-id=caminoLocal`.

### CODE REVIEW

**Comment by c4t-ag** [comment]
@charalarg we had a different plan to solve this:
Because kopernikus will always run (from concept) with an external genesis file, kopernikus default genesis should be exactly this what is done with this PR.
-> CaminoLocal IS kopernikus.

**Comment by charalarg** [comment]
> @charalarg we had a different plan to solve this: Because kopernikus will always run (from concept) with an external genesis file, kopernikus default genesis should be exactly this what is done with this PR. -> CaminoLocal IS kopernikus.

So if i understood correctly you mean that if i want to set up a local network i should use the `genesis_kopernikus.json`?

**Comment by c4t-ag** [comment]
> 



> So if i understood correctly you mean that if i want to set up a local network i should use the `genesis_kopernikus.json`?

Yes, the current genesis_kopernikus.json is / should be unused, and it should be used for local setups with CAM asset.
This is at least what we started communicating some weeks ago.

There is one thing to clearify: @pnowosie mentioned something called "template" (maybe he uses kopernikus json as some base for his genesis creator). I haven't found this requirement in any of our epics / tasks so it would be good to check with him.

**Comment by charalarg** [comment]
> > 
> 
> > So if i understood correctly you mean that if i want to set up a local network i should use the `genesis_kopernikus.json`?
> 
> Yes, the current genesis_kopernikus.json is / should be unused, and it should be used for local setups with CAM asset. This is at least what we started communicating some weeks ago.
> 
> There is one thing to clearify: @pnowosie mentioned something called "template" (maybe he uses kopernikus json as some base for his genesis creator). I haven't found this requirement in any of our epics / tasks so it would be good to check with him.

Yes sure, i just created this branch by myself for testing purposes, and some people also use it for their tests too, so i thought maybe we need it in dev branch. But i didn't know about this plan regarding kopernikus genesis. So i ll convert it to draft for the time being, thanks.

**Pull request closed without merging**
