### PR TITLE
Patched Fix Blst has logical error in SigValidate in Go bindings

### PR DESCRIPTION
**Pull request by imhunterand**
## Description
The vulnerable function is declared as `SigValidate(sigInfcheck bool) bool` and if called with `sigInfcheck` argument set to `true`, the group-check was omitted. The group-check is required to be performed on untrusted input, because the pairing, the corner-stone operation of the signature scheme, is defined only on points that are members of a specific cyclic group, which is a subset of all the possible points on elliptic curves in question. Submitting an untrusted point outside the group opens up the possibility of accepting an alternative signature for a chosen message.

It should be noted that the SigValidate call is not the only way to perform the group-checks. There are optional checks integrated into various other verification methods, such as Verify, AggregateVerify, etc., as well as signature aggregation methods, such as PairingAggregate*. The reason why there are multiple options is that the group-check is a relatively expensive operation, and application developers are arguably entitled the freedom to choose when it's performed.

```js
func (sig *P2Affine) SigValidate(sigInfcheck bool) bool {
    return (sigInfcheck && !bool(C.blst_p2_affine_is_inf(sig))) ||
           bool(C.blst_p2_affine_in_g2(sig))
```

## Impact
Blst versions v0.3.0 through 0.3.10 failed to perform a signature group-check if the call to SigValidate in the Go bindings was complemented with a check for infinity. Formally speaking, infinity, or the identity element of the elliptic curve group, is a member of the group, and the group-check should allow it. An initial review of blst users on GitHub did not uncover any use of this function with the complementary infinity check. This optional check was added as a convenience feature because despite infinity being a legitimate member of the group, individual signatures should never be infinite (as it is equivalent to having zero for the secret key), and observing one should raise a flag.

### CODE REVIEW

**Comment by peak3d** [comment]
@imhunterand thank you for contributing!
1.) We apply PR only to our dev branch, this is the one we build regulary and run it on Kopernikus and Columbus dev / test networks.
2.) We regulary merge ava-labs improvements into our fork, from what I see the blst version bump has already happened there.
We'll speed up the merge so your finding will automatically go in soon. Thx again for letting us know!

**Comment by imhunterand** [comment]
**Hi!** @peak3d Thank you for your respond, I hope you will be happy nice days. lets mark this request as `merged` for fixing vulnerable.

Best regards,
@imhunterand

**Review by evlekht — CHANGES_REQUESTED** [review]
Can you please change the target branch from `chain4travel` to `dev`?
`dev` is our current development branch, and `chain4travel` is used for releases, so we don't accept merges into `chain4travel`.

**Comment by evlekht** [comment]
Resolved with Cortina merge.

**Pull request closed without merging**
