### PR TITLE
Cleanup after cortina merge, reduce diff with avax

### PR DESCRIPTION
**Pull request by evlekht**
This and https://github.com/chain4travel/caminoethvm/pull/111 are cleanup PRs after cortina merges.
It removes empty-line diff with avax, unnecessary c4t headers, adds missing c4t headers and also adds missing camino prefixes to filenames.
It also removes some old leftovers that made it into dev by accident.
## Additional references
Original PR based on cortina-15 dev
https://github.com/chain4travel/caminogo/pull/347

### CODE REVIEW

**Comment by mo-c4t** [comment]
These files were changed also in the original PR:
api/server/server.go
genesis/bootstrappers_test.go
tests/e2e/p/staking_rewards.go
version/strings.go
vms/platformvm/txs/executor/staker_tx_verification_helpers.go

**Review by Noctunus — DISMISSED** [review]

**Comment by evlekht** [comment]
> These files were changed also in the original PR: api/server/server.go genesis/bootstrappers_test.go tests/e2e/p/staking_rewards.go version/strings.go vms/platformvm/txs/executor/staker_tx_verification_helpers.go

`api/server/server.go` contains our old CORS code, that was removed during other cortinas merges. Since we decided that we don't need it (remember caminojs error log thingy), we can also removed that code now.
WDYT, @Noctunus @mo-c4t  ?

**Comment by evlekht** [comment]
> These files were changed also in the original PR: api/server/server.go genesis/bootstrappers_test.go tests/e2e/p/staking_rewards.go version/strings.go vms/platformvm/txs/executor/staker_tx_verification_helpers.go

`genesis/bootstrappers_test.go`, `tests/e2e/p/staking_rewards.go`, `vms/platformvm/txs/executor/staker_tx_verification_helpers.go` will be added in later cortinas. There is no such file now.

**Comment by evlekht** [comment]
> These files were changed also in the original PR: api/server/server.go genesis/bootstrappers_test.go tests/e2e/p/staking_rewards.go version/strings.go vms/platformvm/txs/executor/staker_tx_verification_helpers.go

`version/string.go` in cortina-15 dev was reverted after cleanup because of CNR version-reading regexp.

**Comment by mo-c4t** [comment]
> > These files were changed also in the original PR: api/server/server.go genesis/bootstrappers_test.go tests/e2e/p/staking_rewards.go version/strings.go vms/platformvm/txs/executor/staker_tx_verification_helpers.go
> 
> `api/server/server.go` contains our old CORS code, that was removed during other cortinas merges. Since we decided that we don't need it (remember caminojs error log thingy), we can also removed that code now. WDYT, @Noctunus @mo-c4t ?

We don't need it if the fix from avax is there. because before cortina wildcard * couldn't be used. but avax introduced a fix for that, I don't know in which cortina that fix is.

**Review by mo-c4t — DISMISSED** [review]

**Review by mo-c4t — APPROVED** [review]

**Pull request merged**
