### PR TITLE
TECH-148: Deposit offers

### PR DESCRIPTION
**Pull request by evlekht**
### Summary

Added initial deposit offers (just testing dummy, not real C4T offers) to genesis and created chain state for them.
Added `GetDepositOffers` rpc request that will return active offers.

### Purpose of change

We plan to add possibility for users to lock their funds and get rewards over time (somewhat like it was with delegating, but the delegating will be removed). This process is called depositing.
In order to deposit they'll need to use some active rule set that defines how long funds will be locked, whats minimum amount to deposit and interest rate on which reward will accumulate from deposited tokens. This rule sets called deposit offers. Offers have start and end date and are active (can be used for depositing) only between them.
In this PR we'r adding this offers to chain state, so platformVM can query them later, when deposit transaction will be implemented. This PR also adds possibility for future feature of adding new offers.

### Solution

Added `depositOffersChainState` - this chain state will store all deposit offers and handle adding new ones (not used yet, but could be used later by dedicated transaction). Its also can be populated from genesis.
Updated all genesis jsons and corresponding structs and methods, so all genesis will have one test deposit offer.
Added `GetDepositOffers` rpc request. It will get all offers from `depositOffersChainState`, filter them and return only active ones.

### Additional context

See the https://c4t.atlassian.net/browse/TECH-148

### CODE REVIEW

**Review by c4t-ag — APPROVED** [review]
Thx @evlekht, the only thing to mention here is that we may want to have a clean / remove function for invalid Offers.
There could be several ways to handle this, but you may need a refCounter (active tx) in either ways to not remove an offer before the last tx is finished.

**Review by c4t-ag — COMMENTED** [review]
Should this PR already include a basic definition of the unbonding period (1/2 year before, 1/2 year after deadline)?

**Comment by evlekht** [comment]
> Should this PR already include a basic definition of the unbonding period (1/2 year before, 1/2 year after deadline)?

I'd better do this with deposit PR where I will actually implement this, because right now I don't have a clear view on it
But if its just a `graduallUnlock bool' then we can add it here. Whats your thought on it?

**Comment by evlekht** [comment]
> Thx @evlekht, the only thing to mention here is that we may want to have a clean / remove function for invalid Offers. There could be several ways to handle this, but you may need a refCounter (active tx) in either ways to not remove an offer before the last tx is finished.

@c4t-ag 
When we was talking with Alex about deposit tasks, he said that we should keep all offers in state, even ones that aren't working anymore. May be I got him wrong? Or you mean something different with invalid offers?
If its about no longer valid offers and you want them to be cleaned from state, than there is 2 points:
1) They could be still needed while there is existing deposits that are using this offer.
2) The right way to remove them, IMO, should be with some "advanceTime"-like transaction. The (1) thing can be solved/optimized, I have a solution in mind, if its needed.

**Comment by c4t-ag** [comment]
> 2\. The right way to remove them, IMO, should be with some "advanceTime"-like transaction. The (1) thing can be solved/optimized, I have a solution in mind, if its needed.

IMO with time based solutions you are always wrong, either to short or too long -> because of this I supposed the refcount.
But I think it can be done "simpler":
At the time a user unbonds everything (tx is not needed anymore) :
- Check if the offers end time is past
- Loop over all other deposit tx and check that no one of these is using the offer
- Remove the offer from internal cache state

We can implement this later, but I think it is good to have the final concept for this already in mind.
If it is a small implementation (I doubt), do it now if there is spare time left :-)

**Comment by evlekht** [comment]
@c4t-ag Great idea! I like that, I'd definitely go with this approach.

> IMO with time based solutions you are always wrong, either to short or too long -> because of this I supposed the refcount.

Well, can't agree with that, because, for example, with advanceTimeTx BuildBlock func always looks for exact time when its needed - we can just modify it to also look for expiring offers and deposits.
But again, your idea is much more simple.

Hm, but it also has flaw: what if there is no active deposit after offer expired? Then we'll never get unlock-tx for that offer.

> Loop over all other deposit tx and check that no one of these is using the offer

Also, this one i'd done differently: its better keep track of last deposit for every offer. So, when we'r unlocking deposit and see if its the one, that mentioned as last deposit for offer, we'r doing removal stuff.

**Pull request closed without merging**
